API_KEY = ""
API_SECRET_KEY = ""
API_PASSPHRASE = ""

SYMBOL = "ETH-USDT"
POSITION_SIZE = 0.001

# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 2

CHECK_ORDERS_FREQUENCY = 0.5