API_KEY = ""
API_SECRET_KEY = ""
API_PASSPHRASE = ""


SYMBOL = "ETH-USDT"
POSITION_SIZE = 0.001 #GRID(ACUMULAR USDT)

INVERSION_TOTAL_USDT=300 #INVERSION TOTAL EN USDT PARA EL SGRID

 #SGRID(ACUMULAR LA MONEDA)
ROUN_ORDER= 7 #DECIMALES DE LA CRYPTO(ej. ETH USA 7)
 
# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 100

CHECK_ORDERS_FREQUENCY = 0.5

INVEST_SIZE=INVERSION_TOTAL_USDT//(NUM_BUY_GRID_LINES+NUM_SELL_GRID_LINES)
